function [L,cot] = cotmatrix_embedded(V,F)

   l = [ ...
     sqrt(sum((V(F(:,2),:)-V(F(:,3),:)).^2,2)) ...
     sqrt(sum((V(F(:,3),:)-V(F(:,1),:)).^2,2)) ...
     sqrt(sum((V(F(:,1),:)-V(F(:,2),:)).^2,2)) ...
     ];
   [L,cot] = cotmatrix_intrinsic(l,F,size(V,1));
end
